### ISSUE TITLE
Expose storage.save

### ISSUE THREAD

**Issue by CsloudX** [TokisanGames/Terrain3D#256] opened 2023-11-27 13:21 UTC
Admin edit: expose the save function to GDScript. 

----
### Terrain3D version

v0.9 dev

### Godot version

v4.2.rc2.mono.official [1ba920fad]

### System information

win10 64bit

### Is the issue reproducable in the demo?

Yes

### Issue description

I'm try save storage by code and I"m not sure is this a bug:
![image](https://github.com/TokisanGames/Terrain3D/assets/35988767/9c2308c6-40c4-40ce-b1e7-f2a8cfd667b2)
It become so bigger size.
![image](https://github.com/TokisanGames/Terrain3D/assets/35988767/403d21e2-3803-4975-b86c-ce25be50b18b)
First was the raw storage resouce.

**Comment by CsloudX** [comment] 2023-11-28 01:35
Oh, I found I can set the flag for reduce size.
![image](https://github.com/TokisanGames/Terrain3D/assets/35988767/d51bf2a4-885f-40af-b6ac-c554076dce68)
So I will and should close this.

**Comment by TokisanGames** [comment] 2023-11-28 04:17
If you're calling the engine classes (eg ResourceSaver), it's not a bug in Terrain3D.

A better report would be a feature request to expose storage::save() to GDScript.

**Comment by TokisanGames** [comment] 2023-11-28 08:35
Fixed in 0a608b0

**Closed by TokisanGames** 2023-11-28 08:35 UTC
Labels: enhancement
