### ISSUE TITLE
Noise not being applied when blending textures without heightmap

### ISSUE THREAD

**Issue by NectoT** [TokisanGames/Terrain3D#466] opened 2024-08-27 20:35 UTC
### Terrain3D version

v0.9.2

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 (NVIDIA; 32.0.15.5585) - 11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz (8 Threads)

### Is the issue reproducable in the demo?

Yes

## The problem

When using albedo textures which do not include an alpha channel, there is a clear linear blending between textures, with or without a sprayed overlayed texture. See the difference between the fully-packed and albedo-only textures below:

![heightmap_curr_shader](https://github.com/user-attachments/assets/bbdaa663-7877-4c1c-8f4c-f009c086abc3)
*A blob of grass with a heightmap*

![no_heightmap_curr_shader](https://github.com/user-attachments/assets/ba23f5de-c6e5-45c7-92ae-7ec0b2c8c5e4)
*A blob of grass with no heightmap*

After looking into the shader code I've noticed lines with weights assigned for blending, with noise texture used:

```glsl
// Adjust final weights by texture's height/depth + noise. 1 lookup
float noise3 = texture(noise_texture, uv*noise3_scale).r;
vec4 weights;
weights.x = blend_weights(weights0.x * weights0.y, clamp(mat[0].alb_ht.a + noise3, 0., 1.));
weights.y = blend_weights(weights0.x * weights1.y, clamp(mat[1].alb_ht.a + noise3, 0., 1.));
weights.z = blend_weights(weights1.x * weights0.y, clamp(mat[2].alb_ht.a + noise3, 0., 1.));
weights.w = blend_weights(weights1.x * weights1.y, clamp(mat[3].alb_ht.a + noise3, 0., 1.));
```

It seems that if a texture doesn't have an alpha channel, it's always being read as fully opaque, and so the code inside `clamp` always evaluates to `1 + noise3`, which is clamped to 1. Before 1dc283c there was only `noise3` as the third argument, so there wasn't (at least I think) a problem like that. If we return to the code before the commit we get this:

![no_heightmap_new_shader](https://github.com/user-attachments/assets/309cae2f-0ef6-4213-9799-5f807de58eb4)
*A blob of grass with no heightmap with updated shader*

While not a significant difference, I think it does matter when high-contrasting textures are involved. If the usage of heightmap in calculating weights here is important, using `mix(mat[0].alb_ht.a, noise3, 0.5)` could be used as an alternative to current `clamp` expression, where the mixing weight could also be potentially turned into a uniform.

**Comment by TokisanGames** [comment] 2024-09-06 04:23
I think this is a duplicate of #351, which is at least inclusive of these discussions. I'm closing this. Please join us over there.

**Closed by TokisanGames** 2024-09-06 04:23 UTC
Labels: shaders
