### ISSUE TITLE
Terrain file size is way to big for github

### ISSUE THREAD

**Issue by Rain-Gayming** [TokisanGames/Terrain3D#462] opened 2024-08-23 19:31 UTC
### Terrain3D version

v0.9.0

### System information

Godot 4.3 Arch Linux

### Is the issue reproducable in the demo?

Not applicable

### Issue description

The terrains file size can reach above 100mb making it too big for github

**Comment by Rain-Gayming** [comment] 2024-08-23 19:32
could this be fixed as saving the map as a height map rather than what ever its saved as currently?
my current terrain is about 800k lines long

**Comment by az-raven** [comment] 2024-08-23 20:24
Did you save the Terrain3DStorage asset as a binary .res file per [the docs](
![image](https://terrain3d.readthedocs.io/en/latest/docs/installation.html#manually-into-your-project)
)? If you don't save it outside the scene (or save it as a .tres, instead of a .res), Godot will save it as text to the disk.

**Comment by Rain-Gayming** [comment] 2024-08-23 20:51
yep 
i made it unique
saved as `world_terrain_storage_1.res` and its current ~800k lines and 115mb

**Comment by az-raven** [comment] 2024-08-23 20:53
How large is the world itself?

**Comment by TokisanGames** [comment] 2024-08-24 02:52
Github restrictions aren't a bug with Terrain3D. They allow larger files with paid accounts. We use a private git server for our game. 

I have a 2kx2k terrain at 18mb. You must have about 25 regions. Binary files don't have "lines". 

The size of individual files will be reduced by pr #374. Making this a duplicate of #159 or #356.

I'll close this unless you don't have 20+ regions.

**Comment by Rain-Gayming** [comment] 2024-08-24 09:54
a private git server? ill look into those

**Comment by TokisanGames** [comment] 2024-08-24 10:23
We use a github clone called Gitea running on a VPS. There are other options as well.
Or just wait for #374.
Closing as a duplicate.

**Closed by TokisanGames** 2024-08-24 10:23 UTC

**Comment by TokisanGames** [comment] 2024-09-08 15:07
Now that #374 and #476 have been merged, your data files will be under 20mb each. The demo data files are 4mb.
