### ISSUE TITLE
Support Heightmaps of Any Texel Density

### ISSUE THREAD

**Issue by ludwigseibt** [TokisanGames/Terrain3D#277] opened 2023-12-16 12:20 UTC
### Description

It would be great if there was an option to support heightmaps of arbitrary texel density. For example a 4k by 4k heightmap that represents a 1km by 1km landscape.

This would enable the creation of terrain in any scale. An example would be "It Takes Two", a game where the player is scaled down and the gameplay happens at a very small scale. A resolution of 1px per meter would not be enough here, but working in realworld model scale is still desirable.

In general this would be useful for very very large terrains and also for very small terrains.

I would be happy to try to implement this myself, if you could point me in the right direction. From reading the code, I think the first step wold be to implement a scaling factor where the world UV gets calculated in the main.glsl. https://github.com/TokisanGames/Terrain3D/blob/1cc15ac819bfde5c703e7ea173aeeac96fdab42c/src/shaders/main.glsl#L114

It might also be neccessary to adjust the density of the landscape mesh depending on heightmap resolution. This might be the much more difficult task.

Thank you for your work on these terrain tools!

**Comment by TokisanGames** [comment] 2023-12-16 13:34
Is there any reason this is not a duplicate of #131 or #77? Also see #198.

>  UV = v_vertex.xz; 

This has to do with the scaling of the textures on the terrain and will do nothing to scale the mesh or heightmap. You can see it is reduced and used here:
https://github.com/TokisanGames/Terrain3D/blob/1cc15ac819bfde5c703e7ea173aeeac96fdab42c/src/shaders/main.glsl#L195

> This might be the much more difficult task.

It is indeed not trivial.

**Comment by ludwigseibt** [comment] 2023-12-16 15:42
I did not see #198 while searching because it was closed, sorry about that. That issue sounds like pretty much the same thing.

#131 talks about mesh density, not texel density. Mesh density can be independent of texel density, but I think the texel density could be added to the issue as the two are related.

#77 to my understanding talks about the size of the regions, not the texel density of the heightmap or the density of the mesh.

Sorry about the misunderstandings, this issue is hard to talk about because of wording (texel, texture, mesh, density, size, scale, etc).

I am unsure if thats viable, but making the default Godot Transformation controls work on the Terrain node would enable us to change these densities all together. In HTerrain, thats how I can achieve different densities.

**Comment by TokisanGames** [comment] 2023-12-16 16:07
Texels are pixels on a texture, as opposed to pixels on a screen. It doesn't have density by itself.
Density is a ratio, and in the case of the mesh, it is the vertices per unit distance.
The only things that exist in this context are the heightmap texture and the mesh. 
You can already import a heightmap of any size up to 16k. 
It's only the density ratio of 1 texture pixel to 1 mesh vertex that is fixed. #131 allows this to be adjustable, so this ticket is a duplicate as was #198.

@tcoxon has a pending branch to enable transformation controls.

**Closed by TokisanGames** 2023-12-16 16:07 UTC
Labels: duplicate

**Comment by ludwigseibt** [comment] 2023-12-16 16:42
Texel density refers to the number of texture pixels (texels) per unit of 3D surface area. 
I am not requesting the uncoupling of the "ratio of 1 texture pixel to 1 mesh vertex". Instead, I am requesting the uncoupling of "1 texel to 1 meter(=unit)". I give up now, I am sure both issues will be fixed at the same time.
