### ISSUE TITLE
MacOS fails to load demo data

### ISSUE THREAD

**Issue by maxwacker** [TokisanGames/Terrain3D#240] opened 2023-10-30 16:45 UTC
### Terrain3D version

v0.8.3-alpha_gd4.1.1

### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

Godot v4.1.2.stable - macOS 14.0.0 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Is the issue reproducable in the demo?

Yes

### Issue description

Hello, thanks to share this great work.
I'm new to Godot. When opening the Terrain3D Demo scene, I got this render :
<img width="1477" alt="Terrain3D_LongBox_Render" src="https://github.com/TokisanGames/Terrain3D/assets/6359219/0e4cf23b-2496-460a-a206-40c4f18f86a2">

**Comment by TokisanGames** [comment] 2023-10-30 18:48
Did we just have this discussion on discord? The problem is Godot didn't load the data. The scene and files are fine. It's either a problem with Godot not loading the scene properly, or your Apple OS security settings not allowing Godot to load it. 

Please read starting from here:
https://discord.com/channels/691957978680786944/1130291534802202735/1168253278094635078

Put `terrain_storage.res` in the storage slot and it will load the height data. You'll have to manually put the grass and rock textures into the texture list to see them. Or build the plugin from source (not a nightly build) so you avoid the problems with your Apple security.

**Comment by Kernonen** [comment] 2024-04-17 12:30
Hello, 
I'm very interesting about solving the Terrain opening on MacOs. I guess also it is a security matter. I don"t have access to your discord link so have no way to read it. 
I'm a bit new with Godot so I would appreciate you give a clear workaround on how to solve this matter on Mac. Thank you !

**Comment by TokisanGames** [comment] 2024-04-17 12:41
@Kernonen You can join our discord at Tokisan.com/discord.

But the work around was already described above immediately below the link. 

This issue is specifically for one user opening the demo. We have other users using macos just fine. 

It's most likely is an issue with the local security configuration. The best solution is probably to build Terrain3D yourself that way you can sign the binary either with your own developer keys, or that of your local machine.

**Comment by TokisanGames** [comment] 2024-07-03 07:06
I'm going to close this since there has been two workarounds provided and no further discussion. It's clearly an apple issue. Future Terrain3D versions are going to have a different storage structure so even this issue and workaround will be out of date.

**Closed by TokisanGames** 2024-07-03 07:06 UTC
Labels: wontfix
