### ISSUE TITLE
Terrain Poly Density

### ISSUE THREAD

**Issue by nelsondev** [TokisanGames/Terrain3D#309] opened 2024-01-30 16:35 UTC
### Description

I'd love for the ability to adjust the size of the quads to allow for lower poly terrain. Smooth terrain is great in most cases, but I'd love to use your plugin for a wider selection of projects. Currently it seems they're set to a specific size, as well as region sizes are locked to 1024.

**Comment by TokisanGames** [comment] 2024-01-31 05:43
Please search before making tickets. Duplicate of #131, implemented by #296. Region size tracked in #77.

**Closed by TokisanGames** 2024-01-31 05:43 UTC
Labels: duplicate
