### ISSUE TITLE
Add terrain splines

### ISSUE THREAD

**Issue by dante900210** [TokisanGames/Terrain3D#427] opened 2024-07-20 12:51 UTC
### Description

Can you add terrain splines and terrain slopes, similar to the terrain tools in Unreal?

**Comment by TokisanGames** [comment] 2024-07-20 12:57
What specifically do you mean by terrain splines and terrain slopes? Slopes can already be created with the slope tool. Isn't this a duplicate of #280 or #129.

**Comment by dante900210** [comment] 2024-07-20 13:12
Oh, sorry. I didn't see where the terrain spline is. You can refer to this website: https://dev.epicgames.com/documentation/en-us/unreal-engine/landscape-splines-in-unreal-engine

**Comment by TokisanGames** [comment] 2024-07-20 13:16
Duplicate #280

**Closed by TokisanGames** 2024-07-20 13:16 UTC
Labels: duplicate

**Comment by dante900210** [comment] 2024-07-20 13:27
OK. Thank you.
