### ISSUE TITLE
Editor tablet pen support

### ISSUE THREAD

**Issue by dkaste** [TokisanGames/Terrain3D#290] opened 2023-12-31 18:51 UTC
### Description

I'm not sure how common it is to edit terrain with a graphics tablet, but it seems pretty natural to me. Godot automatically provides pen information through `InputEventMouseMotion`, which should make this feature pretty straightforward to add.

Pen pressure in particular should be very easy to support. Simply multiply the brush opacity by `InputEventMouseMotion.pressure`, or something along those lines.

There's also pen "tilting" which could change the angle of the brush, I suppose.

**Comment by TokisanGames** [comment] 2024-08-20 04:05
Zylann also uses pressure from the input event.

https://github.com/Zylann/godot_heightmap_plugin/blob/74437e6d1c106adee38f9c0fd0e775759b6e2974/addons/zylann.hterrain/tools/plugin.gd#L502

**Comment by TokisanGames** [comment] 2024-08-20 05:10
Pen pressure support added in https://github.com/TokisanGames/Terrain3D/commit/a67d5801a6d9edc7973f4634d396b7566bd228ea

If pen pressure is non-zero, strength is ignored. This means though that pen pressure cannot draw stronger than 100%, unlike the mouse.

@aristides86 @dkaste Try it in a nightly build. Download the artifact.
https://github.com/TokisanGames/Terrain3D/actions/runs/10465611812

**Comment by aristides86** [comment] 2024-08-28 00:09
Thank you. Pressure works but could it be that it breaks strength for the mouse now? In the video the first stroke made with the stylus with increasing pressure, the second with the mouse with 1% strength. Strength works well in 0.9.2-beta release.

https://github.com/user-attachments/assets/81a84fe6-7e7b-4eeb-9a0e-af3fac543f85

**Comment by TokisanGames** [comment] 2024-08-28 09:38
This looks beautiful. Please send me info so I can include it here
https://terrain3d.readthedocs.io/en/latest/docs/games.html

In 0.9.3-dev raise/lower strength was reduced 90%. However, you can increase strength up to 10,000%.

I can reproduce the issue. The current code says:
* If mouse_pressure is >0 use it, else use brush_strength

The problem is that if the mouse is clicked, pen pressure is 1 instead of 0. And when the tablet is pressed, godot reports that as the left mouse button. I see no way to determine if the user is moving the pen or the mouse when pressure is 0 or 1.

So which is better:
* effective strength = mouse_pressure * brush_strength
* effective strength = mouse_pressure if 0-.999; brush_strength if 1
* or ?

The first means brush strength applies to the pen and the mouse. The second means it does not unless you press really hard. Then between .999 and 1.0 the mouse strength will jump. This is probably the worst option.

**Comment by aristides86** [comment] 2024-08-28 10:09
To make pressure work we need to enable Pen driver in the project settings, so Godot can understand if the pen or mouse is currently being used. Without it any input is a mouse. Can it be a switch for tablet/mouse input? This would also make it possible to use the Strength parameter for both mouse and tablet input, so users don't have to adjust pressure sensitivity in their tablet settings.

**Comment by TokisanGames** [comment] 2024-08-28 21:08
I didn't know about the project settings. However using my Huion tablet, regardless of if I use project settings / pen tablet `none`, `wintab`, or `winink`, all three options report a pen click as left mouse button, and provide pressure.

.001-.999 pressure isn't the problem. I know it's a pen with those values, and 0 doesn't matter. I have no way to determine if 1 is a pen or a mouse. I wanted 1 * brush_strength for a mouse and 1 for a pen. My question is can we do 1 * brush_strength for both? Then I don't need to care if it's a mouse or a pen, it's the same.

> This would also make it possible to use the Strength parameter for both mouse and tablet input, so users don't have to adjust pressure sensitivity in their tablet settings.

It sounds like you would like 1 * brush_strength as well, which means the strength slider works for the pen. I was concerned 
 this wouldn't work well in usage, but trying it I see it does works well. Plus it gives access to brush strengths > 100%. So I'll do this tomorrow.

The operation will be:
* If mouse_pressure is 0, use brush_strength (this allows 1-click operations at full strength from the mouse, eg alpha stamps)
* Else use mouse_pressure * brush_strength

**Comment by TokisanGames** [comment] 2024-08-29 10:54
> The operation will be:
> If mouse_pressure is 0, use brush_strength (this allows 1-click operations at full strength from the mouse, eg alpha stamps)
> Else use mouse_pressure * brush_strength

This works fine most of the time. Mouse clicks have 0 pressure, mouse down w/ movement have 1 pressure. Pen is usually .001-1. Also, unlike the mouse, the pen seems to be constantly sending move events.

However, on my tablet it often registers a 0 pressure click at the start and end of a stroke, but not always. This means at the start or right at the end it suddenly goes full strength. In use, I don't it as an issue at start, but I have noticed it at the end.

What I'm doing now is, tracking the time of the last pen movement (pressure .001-.999). If a 0 pressure click comes in > 100ms after the last pen movement, then pressure is inverted to 1 for full strength. So far, this allows every mouse click and cuts off almost all of the pen jumps at the end of strokes.

I think this is a fair compromise. But I really wish Godot had better identification of tablet and mice input. Even if mouse clicks reported a pressure of 1 would be sufficient to avoid this extra tracking.

Fixed in 59b681ef3bb7cc464dd09c6500fc189d4c38fcba

**Closed** 2024-08-29 10:54 UTC
Labels: enhancement, good first issue
